// waf-signatures.ts — Web Application Firewall detection signatures
// Detects WAF presence through response headers, cookies, and body content patterns.

export interface WafSignature {
  /** WAF product name */
  name: string;
  /** Vendor / company behind the WAF */
  vendor: string;
  /** Detection patterns across response components */
  patterns: {
    /** Response header name -> regex pattern for the value */
    headers?: Record<string, string>;
    /** Cookie name patterns (regex) to look for in Set-Cookie headers */
    cookies?: string[];
    /** Regex patterns to match in the response body (block pages, etc.) */
    body?: string[];
    /** HTTP status codes commonly returned when WAF blocks a request */
    status?: number[];
  };
  /** Confidence score from 0.0 to 1.0 */
  confidence: number;
}

export const WAF_SIGNATURES: WafSignature[] = [
  // ── Cloudflare ─────────────────────────────────────────────────────────
  {
    name: "Cloudflare",
    vendor: "Cloudflare, Inc.",
    patterns: {
      headers: {
        "cf-ray": "^[0-9a-f]+-[A-Z]{3}$",
        server: "^cloudflare$",
        "cf-cache-status": "^(HIT|MISS|DYNAMIC|EXPIRED|BYPASS)$",
      },
      cookies: [
        "^__cf_bm$",
        "^cf_chl_.*$",
        "^__cfduid$",
        "^cf_clearance$",
      ],
      body: [
        "Attention Required! \\| Cloudflare",
        "Enable JavaScript and cookies to continue",
        "cloudflare\\.com\\/cdn-cgi\\/",
        "cf-error-details",
        "Ray ID: [0-9a-f]+",
      ],
      status: [403, 503, 1020],
    },
    confidence: 0.95,
  },

  // ── AWS WAF ────────────────────────────────────────────────────────────
  {
    name: "AWS WAF",
    vendor: "Amazon Web Services",
    patterns: {
      headers: {
        "x-amzn-requestid": "^[0-9a-f-]{36}$",
        "x-amzn-trace-id": "^Root=",
        "x-amz-cf-id": ".*",
      },
      body: [
        "Request blocked",
        "<!DOCTYPE html>.*?<p>If you believe.*?AWS",
        "automated access to this page was denied",
        "#[0-9a-f-]{36}",
      ],
      status: [403],
    },
    confidence: 0.8,
  },

  // ── ModSecurity ────────────────────────────────────────────────────────
  {
    name: "ModSecurity",
    vendor: "Trustwave / OWASP",
    patterns: {
      headers: {
        server: "Mod_Security|NOYB",
      },
      body: [
        "ModSecurity",
        "Mod_Security",
        "This error was generated by Mod_Security",
        "Not Acceptable!.*The requested URL",
        "rules of the mod_security module",
      ],
      status: [403, 406],
    },
    confidence: 0.9,
  },

  // ── Imperva / Incapsula ────────────────────────────────────────────────
  {
    name: "Imperva Incapsula",
    vendor: "Imperva",
    patterns: {
      headers: {
        "x-cdn": "^Imperva$",
        "x-iinfo": ".*",
      },
      cookies: [
        "^visid_incap_\\d+$",
        "^incap_ses_\\d+_\\d+$",
        "^___utmvc$",
        "^nlbi_\\d+$",
      ],
      body: [
        "Incapsula incident ID",
        "Powered By Incapsula",
        "_Incapsula_Resource",
        "Request unsuccessful\\.\\s*Incapsula",
      ],
      status: [403],
    },
    confidence: 0.9,
  },

  // ── Akamai ─────────────────────────────────────────────────────────────
  {
    name: "Akamai",
    vendor: "Akamai Technologies",
    patterns: {
      headers: {
        server: "^AkamaiGHost$",
        "x-akamai-transformed": ".*",
        "akamai-x-cache-on": ".*",
        "akamai-x-cache-remote-on": ".*",
        "x-check-cacheable": ".*",
      },
      body: [
        "Reference #18\\.[0-9a-f]+\\.[0-9a-f]+\\.[0-9a-f]+",
        "Access Denied.*You don't have permission",
        "AkamaiGHost",
      ],
      status: [403],
    },
    confidence: 0.85,
  },

  // ── F5 BIG-IP ASM ──────────────────────────────────────────────────────
  {
    name: "F5 BIG-IP ASM",
    vendor: "F5 Networks",
    patterns: {
      headers: {
        server: "^BigIP$|^BIG-IP$",
        "x-wa-info": ".*",
      },
      cookies: [
        "^TS[0-9a-f]{6,8}$",
        "^BIGipServer.*$",
        "^MRHSession$",
        "^LastMRH_Session$",
      ],
      body: [
        "The requested URL was rejected",
        "Please consult with your administrator",
        "Your support ID is:",
        "F5 Networks",
      ],
      status: [403],
    },
    confidence: 0.85,
  },

  // ── Fortinet FortiWeb ──────────────────────────────────────────────────
  {
    name: "FortiWeb",
    vendor: "Fortinet",
    patterns: {
      headers: {
        server: "FortiWeb",
      },
      cookies: [
        "^FORTIWAFSID$",
        "^cookiesession1$",
      ],
      body: [
        "FortiWeb",
        "The page you are requesting cannot be served",
        "\\.fgd_icon",
        "fortigate",
      ],
      status: [403],
    },
    confidence: 0.85,
  },

  // ── Sucuri ─────────────────────────────────────────────────────────────
  {
    name: "Sucuri WAF",
    vendor: "Sucuri (GoDaddy)",
    patterns: {
      headers: {
        "x-sucuri-id": ".*",
        "x-sucuri-cache": "^(HIT|MISS)$",
        server: "^Sucuri\\/Cloudproxy$",
      },
      body: [
        "Access Denied - Sucuri Website Firewall",
        "Sucuri WebSite Firewall",
        "sucuri\\.net\\/privacy",
        "CloudProxy",
        "If you are the site owner.*Sucuri",
      ],
      status: [403],
    },
    confidence: 0.9,
  },

  // ── Barracuda WAF ──────────────────────────────────────────────────────
  {
    name: "Barracuda WAF",
    vendor: "Barracuda Networks",
    patterns: {
      headers: {
        server: "^Barracuda",
      },
      cookies: [
        "^barra_counter_session$",
        "^BNI__BARRACUDA_LB_COOKIE$",
        "^BNI_persistence$",
      ],
      body: [
        "You are being blocked",
        "Barracuda Networks",
        "You have been blocked.*barracuda",
      ],
      status: [403],
    },
    confidence: 0.85,
  },

  // ── Wallarm ────────────────────────────────────────────────────────────
  {
    name: "Wallarm",
    vendor: "Wallarm",
    patterns: {
      headers: {
        "x-wallarm-waf-check": ".*",
        server: "nginx-wallarm",
      },
      body: [
        "wallarm",
        "nginx-wallarm",
      ],
      status: [403],
    },
    confidence: 0.8,
  },

  // ── Signal Sciences ────────────────────────────────────────────────────
  {
    name: "Signal Sciences",
    vendor: "Signal Sciences (Fastly)",
    patterns: {
      headers: {
        "x-sigsci-tags": ".*",
        "x-sigsci-decisionscore": "\\d+",
        "x-sigsci-requestid": ".*",
      },
      body: [
        "Signal Sciences",
      ],
      status: [406],
    },
    confidence: 0.85,
  },

  // ── DDoS-Guard ─────────────────────────────────────────────────────────
  {
    name: "DDoS-Guard",
    vendor: "DDoS-Guard",
    patterns: {
      headers: {
        server: "^ddos-guard$",
        "x-ddos-protection": ".*",
      },
      cookies: [
        "^__ddg[0-9]+$",
        "^__ddgid_$",
        "^__ddgmark_$",
      ],
      body: [
        "DDoS-Guard",
        "ddos-guard\\.net",
      ],
      status: [403],
    },
    confidence: 0.85,
  },

  // ── Wordfence ──────────────────────────────────────────────────────────
  {
    name: "Wordfence",
    vendor: "Defiant Inc.",
    patterns: {
      headers: {},
      body: [
        "Generated by Wordfence",
        "wordfence\\.com",
        "This response was generated by Wordfence",
        "Your access to this site has been limited by the site owner",
        "wfwaf-authcookie-",
      ],
      status: [403, 503],
    },
    confidence: 0.9,
  },

  // ── Comodo WAF ─────────────────────────────────────────────────────────
  {
    name: "Comodo WAF",
    vendor: "Comodo (Sectigo)",
    patterns: {
      headers: {
        server: "^Protected by Comodo",
      },
      body: [
        "Protected by Comodo",
        "Comodo WAF",
        "You have been blocked.*Comodo",
      ],
      status: [403],
    },
    confidence: 0.8,
  },

  // ── StackPath ──────────────────────────────────────────────────────────
  {
    name: "StackPath",
    vendor: "StackPath",
    patterns: {
      headers: {
        "x-sp-waf": ".*",
        "x-sp-url": ".*",
        server: "StackPath",
      },
      cookies: [
        "^sp_waf_sid$",
      ],
      body: [
        "StackPath",
        "You performed an action that triggered.*StackPath",
      ],
      status: [403],
    },
    confidence: 0.8,
  },
];
